mv /etc/nova/nova.conf.orig /etc/nova/nova.conf
mv /etc/nova/api-paste.ini.orig /etc/nova/api-paste.ini
mv /etc/cinder/cinder.conf.orig /etc/cinder/cinder.conf
mv /etc/cinder/api-paste.ini.orig /etc/cinder/api-paste.ini
mv /etc/keystone/keystone.conf.orig /etc/keystone/keystone.conf
mv /etc/neutron/neutron.conf.orig /etc/neutron/neutron.conf
mv /etc/neutron/api-paste.ini.orig /etc/neutron/api-paste.ini
mv /etc/ceilometer/ceilometer.conf.orig /etc/ceilometer/ceilometer.conf
mv /etc/ceilometer/api_paste.ini.orig /etc/ceilometer/api_paste.ini
mv /etc/glance/glance-cache.conf.orig /etc/glance/glance-cache.conf
mv /etc/glance/glance-api.conf.orig /etc/glance/glance-api.conf
mv /etc/glance/glance-registry.conf.orig /etc/glance/glance-registry.conf
mv /etc/glance/glance-scrubber.conf.orig /etc/glance/glance-scrubber.conf
