# Goldstone Docker Compose Configuration
# Copyright 2015 Solinea, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '2'

services:

  #
  # Goldstone Server Container
  #
  gsapp:
    build: ./docker/goldstone-app-e
    env_file: ./docker/config/goldstone-dev.env
    volumes:
      - .:/home/app
      - ./docker/goldstone-base/config:/home/app/config
    ports:
      - "8000:8000"
    links:
      - gsdb
      - gssearch
      - gslog
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "10"

  #
  # Database Container
  #
  gsdb:
    build: ./docker/goldstone-db
    env_file: ./docker/config/goldstone-dev.env
    ports:
      - "5432:5432"
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "10"

  #
  # Logstash Container
  #
  gslog:
    build: ./docker/goldstone-log
    volumes:
      - ./docker/goldstone-log/conf.d:/logstash/conf.d
      - ./docker/goldstone-log/patterns:/opt/logstash/patterns
    ports:
      - "5514:5514"
      - "5515:5515"
      - "5516:5516"
      - "5517:5517/udp"
    links:
      - gssearch
      - gstaskq
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "10"

  #
  # Elasticsearch Container
  #
  gssearch:
    build: ./docker/goldstone-search
    volumes:
      - ./docker/goldstone-search/config:/usr/share/elasticsearch/config
    ports:
      - "9200:9200"
      - "9300:9300"
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "10"

  #
  # Celery container
  # 
  gstask:
    build: ./docker/goldstone-task
    env_file: ./docker/config/goldstone-dev.env
    volumes:
      - .:/home/app
      - ./docker/goldstone-base/config:/home/app/config
    links:
      - gsdb
      - gssearch
      - gstaskq
      - gslog
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "10"

  #
  # Celery Task Queue Container
  #
  gstaskq:
    build: ./docker/goldstone-task-queue
    ports:
      - "6379:6379"
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "10"

  #
  # Canary Container
  #
  gscanary:
    image: gs-docker-ent.bintray.io/goldstone-canary:latest
    env_file: ./docker/config/goldstone-dev.env
    links:
      - gslog
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "10"

  #
  # Kibana for developer debugging
  #
  gskibana:
    image: kibana:4.1
    env_file: ./docker/config/goldstone-dev.env
    ports:
      - "5601:5601"
    depends_on:
      - gssearch
    links:
      - gssearch
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "10"
