# Goldstone Docker Compose Configuration
# Copyright 2015 Solinea, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Goldstone Proxy & Static
gsweb:
  image: solinea/goldstone-web
  volumes:
    - ./config/goldstone-web/nginx.conf:/etc/nginx/nginx.conf
    - ./config/goldstone-web/conf.d:/etc/nginx/conf.d
  ports:
    - "8888:8888"
  links:
    - gsapp:gsapp
  log_driver: "syslog"

# Goldstone Server Container
gsapp:
  image: solinea/goldstone-app
  env_file: ./config/goldstone-prod.env
  ports:
    - "8000:8000"
  links:
    - gsdb
    - gssearch
  log_driver: "syslog"

# Database Container
gsdb:
  image: solinea/goldstone-db
  env_file: ./config/goldstone-prod.env
  volumes_from:
    - gsdbdvc
  ports:
    - "5432:5432"
  log_driver: "syslog"

# Database Data Volume Container
gsdbdvc:
  image: solinea/goldstone-db-dvc
  volumes:
    - /var/lib/postgresql/data
  log_driver: "syslog"

# Logstash Container
gslog:
  image: solinea/goldstone-log
  command: logstash -f /logstash/conf.d -w 1
  volumes:
    - ./config/goldstone-log/conf.d:/logstash/conf.d
    - ./config/goldstone-log/patterns:/opt/logstash/patterns
  ports:
    - "5514:5514"
    - "5515:5515"
    - "5516:5516"
  links:
    - gssearch
  log_driver: "syslog"

# Elasticsearch Container
gssearch:
  image: solinea/goldstone-search
  volumes:
    - ./config/goldstone-search:/usr/share/elasticsearch/config
    # Mount a local volume for data
    #- "$PWD/data/goldstone-search":/usr/share/elasticsearch/data
  ports:
    - "9200:9200"
    - "9300:9300"
  log_driver: "syslog"

# Celery Worker Container
gstask:
  image: solinea/goldstone-task
  env_file: ./config/goldstone-prod.env
  links:
    - gstaskq
    - gssearch
    - gsdb
  log_driver: "syslog"

# Celery Task Queue Container
gstaskq:
 image: solinea/goldstone-task-queue
 ports:
    - "6379:6379"
 log_driver: "syslog"
