# Goldstone Docker Compose Configuration

# Elasticsearch Container
elasticsearch:
  image: solinea/goldstone-elasticsearch:develop
  volumes:
    - config/elasticsearch:/usr/share/elasticsearch/config
    # Mount a local volume for data
    #- "$PWD/data/es":/usr/share/elasticsearch/data
  ports:
    - "9200:9200"
    - "9300:9300"

# PostgreSQL Container
postgres:
  image: solinea/goldstone-postgres:develop
  env_file: config/postgres/pgsql.env
  volumes_from:
    - pgdvc
  ports:
    - "5432:5432"

# PostgreSQL Data Volume Container
pgdvc:
  image: solinea/goldstone-postgres-data:develop
  volumes:
    - /var/lib/postgresql/data

# Redis Container
redis:
  image: redis:develop
  volumes_from:
    - redisdvc
  ports:
    - "6379:6379"

# Redis Data Volume Container
redisdvc:
  image: solinea/goldstone-redis-data
  volumes:
    - /data

# Logstash Container
logstash:
  image: solinea/goldstone-logstash:develop
  command: logstash -f /logstash/conf.d -w 1
  volumes:
    - config/logstash/conf.d:/logstash/conf.d
    - config/logstash/patterns:/opt/logstash/patterns
  ports:
    - "5514:5514"
    - "5515:5515"
    - "5516:5516"
  links:
    - elasticsearch
    - elasticsearch:es

# Goldstone Django App Container
goldstone:
  image: solinea/goldstone:develop
  ports:
    - "80:8000"
  links:
    - postgres
    - postgres:pgsql-server
    - elasticsearch
    - elasticsearch:es

# Celery Worker Container
#celery:
#image: solinea/goldstone:develop
#command: celery worker -A celery.py -Q default -n default@%h --loglevel=info
#links:
#- redis

# Static Web Content Container
#static:
#image: solinea/goldstone:develop

# RabbitMQ Container
#rabbit1:
#  image: rabbitmq:3-management
#  hostname: rabbit1
#  ports:
#    - "5672:5672"
#    - "15672:15672"
