# Goldstone Docker Compose Configuration
# Copyright 2015 Solinea, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '2'

services:

  # Goldstone Proxy & Static
  gsweb:
    image: solinea/goldstone-web:1.1.1-SNAPSHOT.286.gb2546eb.prepkg.cleanup
    ports:
      - "8443:8443"
    links:
      - gsapp:gsapp
    logging:
      driver: "syslog"
      options:
        syslog-facility: "local0"
        tag: "gsweb"

  # Goldstone Server Container
  gsapp:
    image: gs-docker-ent.bintray.io/goldstone-app-e:1.1.1-SNAPSHOT.286.gb2546eb.prepkg.cleanup
    env_file: ./config/goldstone-prod.env
    ports:
      - "8000:8000"
    links:
      - gsdb
      - gssearch
      - gstaskq
      - gslog
    logging:
      driver: "syslog"
      options:
        syslog-facility: "local0"
        tag: "gsapp"

  # Database Container
  gsdb:
    image: solinea/goldstone-db:1.1.1-SNAPSHOT.286.gb2546eb.prepkg.cleanup
    env_file: ./config/goldstone-prod.env
    volumes:
      - /var/lib/goldstone/sql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    logging:
      driver: "syslog"
      options:
        syslog-facility: "local0"
        tag: "gsdb"

  # Logstash Container
  gslog:
    image: solinea/goldstone-log:1.1.1-SNAPSHOT.286.gb2546eb.prepkg.cleanup
    ports:
      - "5514:5514"
      - "5515:5515"
      - "5516:5516"
      - "5517:5517/udp"
    links:
      - gssearch
    logging:
      driver: "syslog"
      options:
        syslog-facility: "local0"
        tag: "gslog"

  # Elasticsearch Container
  gssearch:
    image: solinea/goldstone-search:1.1.1-SNAPSHOT.286.gb2546eb.prepkg.cleanup
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - /var/lib/goldstone/es_data:/usr/share/elasticsearch/data
    logging:
      driver: "syslog"
      options:
        syslog-facility: "local0"
        tag: "gssearch"

  # Celery Task Queue Container
  gstaskq:
    image: solinea/goldstone-task-queue:1.1.1-SNAPSHOT.286.gb2546eb.prepkg.cleanup
    ports:
      - "6379:6379"
    logging:
      driver: "syslog"
      options:
        syslog-facility: "local0"
        tag: "gstaskq"

  #
  # Celery container
  #
  gstask:
    image: gs-docker-ent.bintray.io/goldstone-task-e:1.1.1-SNAPSHOT.286.gb2546eb.prepkg.cleanup
    env_file: ./config/goldstone-prod.env
    links:
      - gsdb
      - gssearch
      - gstaskq
      - gslog
    logging:
      driver: "syslog"
      options:
        syslog-facility: "local0"
        tag: "gstask"

  #
  # Canary Container
  #
  gscanary:
    image: gs-docker-ent.bintray.io/goldstone-svc-canary:stable
    env_file: ./config/goldstone-prod.env
    links:
      - gslog
    logging:
      driver: "syslog"
      options:
        syslog-facility: "local0"
        tag: "gscanary"
