# Goldstone Docker Compose Configuration
# Copyright 2015 Solinea, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Goldstone Proxy & Static
gsweb:
  image: solinea/goldstone-web:0.8.3-SNAPSHOT
  ports:
    - "8888:8888"
  links:
    - gsapp:gsapp
  log_driver: "syslog"
  log_opt:
    syslog-facility: "local0"
    syslog-tag: "gsweb"

# Goldstone Server Container
gsapp:
  image: gs-docker-ent.bintray.io/goldstone-app-e:0.8.3-SNAPSHOT
  env_file: ./config/goldstone-prod.env
  ports:
    - "8000:8000"
  links:
    - gsdb
    - gssearch
    - gstaskq
  log_driver: "syslog"
  log_opt:
    syslog-facility: "local0"
    syslog-tag: "gsapp"

# Database Container
gsdb:
  image: solinea/goldstone-db:0.8.3-SNAPSHOT
  env_file: ./config/goldstone-prod.env
  volumes_from:
    - gsdbdvc
  ports:
    - "5432:5432"
  log_driver: "syslog"
  log_opt:
    syslog-facility: "local0"
    syslog-tag: "gsdb"

# Database Data Volume Container
gsdbdvc:
  image: solinea/goldstone-db:0.8.3-SNAPSHOT
  entrypoint: /bin/true
  volumes:
    - /var/lib/postgresql/data
  log_driver: "syslog"
  log_opt:
    syslog-facility: "local0"
    syslog-tag: "gsdbdvc"

# Logstash Container
gslog:
  image: solinea/goldstone-log:0.8.3-SNAPSHOT
  ports:
    - "5514:5514"
    - "5515:5515"
    - "5516:5516"
  links:
    - gssearch
  log_driver: "syslog"
  log_opt:
    syslog-facility: "local0"
    syslog-tag: "gslog"

# Elasticsearch Container
gssearch:
  image: solinea/goldstone-search:0.8.3-SNAPSHOT
  ports:
    - "9200:9200"
    - "9300:9300"
  log_driver: "syslog"
  log_opt:
    syslog-facility: "local0"
    syslog-tag: "gssearch"

# Celery Task Queue Container
gstaskq:
  image: solinea/goldstone-task-queue:0.8.3-SNAPSHOT
  ports:
    - "6379:6379"
  log_driver: "syslog"
  log_opt:
    syslog-facility: "local0"
    syslog-tag: "gstaskq"
