---
- hosts: openstack
  sudo: True
  user: vagrant
  gather_facts: no

  tasks:

  - name: copy backup_rdo_config.sh files
    copy: src=/home/vagrant/backup_rdo_config.sh dest=/home/vagrant/ owner=vagrant group=vagrant mode=0777

  - name: execute revert_openstack.sh
    command: sh /home/vagrant/backup_rdo_config.sh


   
