#! /bin/bash
# Copyright 2015 Solinea, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [[ ! -f "goldstone-server.spec" ]]; then
   echo "Run $0 from top of source tree."
   exit 255
fi

if [[ "X$GOLDSTONE_PKG_VERSION" == "X" || "X$GOLDSTONE_PKG_RELEASE" == "X" ]] ; then
    echo "GOLDSONE_PKG_VERSION and/or GOLDSONE_PKG_RELEASE not set."
    exit 254
fi

rpmbuild -bb --define "_topdir `pwd`/rpmbuild" --define "_sourcedir `pwd`" goldstone-server.spec
