# encoding: utf-8

# -*- mode: ruby -*-
# vi: set ft=ruby :

# This vagrantfile is for **DEVELOPMENT** version of goldstone 
# on a CentOS 6.5 image

Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 1
  end

  config.vm.define "goldstone", primary: true do |goldstone|
    goldstone.vm.box = "centos65-x86_64"
    goldstone.vm.box_url = "https://github.com/2creatives/vagrant-centos/releases/download/v6.5.3/centos65-x86_64-20140116.box"
    goldstone.vm.network :forwarded_port, guest: 80, host: 8080
    goldstone.vm.network :forwarded_port, guest: 8000, host: 8888
    goldstone.vm.network :forwarded_port, guest: 9200,    host: 9201
    goldstone.vm.network "private_network", ip: "192.168.1.2", virtualbox__intnet: "private"
    # install prerequesites (EPEL already enabled)
    goldstone.vm.provision :shell, :inline => "yum install -y yum install -y gcc gcc-c++ mysql-server mysql-devel"
    # install goldstone
    goldstone.vm.provision :shell, :inline => "yum install -y http://repo.solinea.com/repo/goldstone_repos-1.1-1.noarch.rpm"
    # Mount RPM folder to install new RPM
    # Change this to your Dropbox folder if it is in a different place
    goldstone.vm.synced_folder "~/Dropbox/Solinea\ Management/Products/RPMs/", "/goldstone"
  end

  config.vm.define "rdo" do |rdo|
    rdo.vm.box = "rdo-icehouse-allinone-062914"
    rdo.vm.box_url = "http://repo.solinea.com/rdo-icehouse-allinone-062914.box"
    rdo.vm.network "private_network", ip: "192.168.1.3", virtualbox__intnet: "private"
    rdo.vm.network :forwarded_port, guest: 80,    host: 8081
    rdo.vm.network :forwarded_port, guest: 5000,  host: 5000
    rdo.vm.network :forwarded_port, guest: 35357, host: 35357
    rdo.vm.network :forwarded_port, guest: 9292,  host: 9292
    rdo.vm.network :forwarded_port, guest: 8773,  host: 8773
    rdo.vm.network :forwarded_port, guest: 8774,  host: 8774
    rdo.vm.network :forwarded_port, guest: 8775,  host: 8775
    rdo.vm.network :forwarded_port, guest: 8776,  host: 8776
    rdo.vm.network :forwarded_port, guest: 8777,  host: 8777
    rdo.vm.network :forwarded_port, guest: 6080,  host: 6080
    rdo.vm.network :forwarded_port, guest: 9696,  host: 9696
    # rdo.vm.network :forwarded_port, guest: 8000,  host: 8000
    # rdo.vm.network :forwarded_port, guest: 8004,  host: 8004
  end

end
