#!/bin/bash

case $1 in
  start)
    if [ -z "$GOLDSTONE_REPO_USER" ] || [ -z "$GOLDSTONE_REPO_PASS" ] || [ -z "$GOLDSTONE_REPO_USER" ]; then
    	echo "GOLDSTONE_REPO_USER and GOLDSTONE_REPO_PASS environment variables must be set:"
    	echo "  $ export GOLDSTONE_REPO_USER=myusername"
    	echo "  $ export GOLDSTONE_REPO_PASS=myrepopassword"
  	  exit 1
    fi
    echo "Logging in to Goldstone enterprise docker repo"
    docker login -u "${GOLDSTONE_REPO_USER}" -p "${GOLDSTONE_REPO_PASS}" gs-docker-ent.bintray.io
    echo "Starting Goldstone Server Enterprise ..."
    /opt/goldstone/bin/docker-compose -f /opt/goldstone/docker-compose.yml up
    echo "DONE"
    ;;
  stop)
    echo "Stopping Goldstone Server Enterprise ..."
    /opt/goldstone/bin/docker-compose -f /opt/goldstone/docker-compose.yml stop
    echo "DONE"
    ;;
  version)
    rpm -qil goldstone-server-enterprise | grep -E "Version|Release"
    ;;
  *)
    echo $"Usage: $0 {start|stop|version}"
    exit 1
esac
