# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addon',
            name='polyresource_ptr',
        ),
        migrations.RemoveField(
            model_name='aggregate',
            name='polyresource_ptr',
        ),
        migrations.RemoveField(
            model_name='availabilityzone',
            name='polyresource_ptr',
        ),
        migrations.RemoveField(
            model_name='cinder',
            name='polyresource_ptr',
        ),
        migrations.RemoveField(
            model_name='cloudpipe',
            name='polyresource_ptr',
        ),
        migrations.RemoveField(
            model_name='credential',
            name='polyresource_ptr',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='polyresource_ptr',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='polyresource_ptr',
        ),
        migrations.RemoveField(
            model_name='flavor',
            name='polyresource_ptr',
        ),
        migrations.RemoveField(
            model_name='glance',
            name='polyresource_ptr',
        ),
        migrations.RemoveField(
            model_name='group',
            name='polyresource_ptr',
        ),
        migrations.RemoveField(
            model_name='host',
            name='polyresource_ptr',
        ),
        migrations.RemoveField(
            model_name='hypervisor',
            name='polyresource_ptr',
        ),
        migrations.RemoveField(
            model_name='image',
            name='polyresource_ptr',
        ),
        migrations.RemoveField(
            model_name='interface',
            name='polyresource_ptr',
        ),
        migrations.RemoveField(
            model_name='keypair',
            name='polyresource_ptr',
        ),
        migrations.RemoveField(
            model_name='keystone',
            name='polyresource_ptr',
        ),
        migrations.RemoveField(
            model_name='limits',
            name='polyresource_ptr',
        ),
        migrations.RemoveField(
            model_name='neutron',
            name='polyresource_ptr',
        ),
        migrations.RemoveField(
            model_name='neutronagent',
            name='polyresource_ptr',
        ),
        migrations.RemoveField(
            model_name='neutronextension',
            name='polyresource_ptr',
        ),
        migrations.RemoveField(
            model_name='neutronfloatingip',
            name='polyresource_ptr',
        ),
        migrations.RemoveField(
            model_name='neutronnetwork',
            name='polyresource_ptr',
        ),
        migrations.RemoveField(
            model_name='neutronport',
            name='polyresource_ptr',
        ),
        migrations.RemoveField(
            model_name='neutronquota',
            name='polyresource_ptr',
        ),
        migrations.RemoveField(
            model_name='neutronrouter',
            name='polyresource_ptr',
        ),
        migrations.RemoveField(
            model_name='neutronsecuritygroup',
            name='polyresource_ptr',
        ),
        migrations.RemoveField(
            model_name='neutronsecuritygrouprule',
            name='polyresource_ptr',
        ),
        migrations.RemoveField(
            model_name='neutronsubnet',
            name='polyresource_ptr',
        ),
        migrations.RemoveField(
            model_name='neutronsubnetpool',
            name='polyresource_ptr',
        ),
        migrations.RemoveField(
            model_name='nova',
            name='polyresource_ptr',
        ),
        migrations.RemoveField(
            model_name='novalimits',
            name='polyresource_ptr',
        ),
        migrations.RemoveField(
            model_name='polyresource',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='project',
            name='polyresource_ptr',
        ),
        migrations.RemoveField(
            model_name='qosspec',
            name='polyresource_ptr',
        ),
        migrations.RemoveField(
            model_name='quotaset',
            name='polyresource_ptr',
        ),
        migrations.RemoveField(
            model_name='region',
            name='polyresource_ptr',
        ),
        migrations.RemoveField(
            model_name='role',
            name='polyresource_ptr',
        ),
        migrations.RemoveField(
            model_name='server',
            name='polyresource_ptr',
        ),
        migrations.RemoveField(
            model_name='servergroup',
            name='polyresource_ptr',
        ),
        migrations.RemoveField(
            model_name='service',
            name='polyresource_ptr',
        ),
        migrations.RemoveField(
            model_name='snapshot',
            name='polyresource_ptr',
        ),
        migrations.RemoveField(
            model_name='token',
            name='polyresource_ptr',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='polyresource_ptr',
        ),
        migrations.RemoveField(
            model_name='user',
            name='polyresource_ptr',
        ),
        migrations.RemoveField(
            model_name='volume',
            name='polyresource_ptr',
        ),
        migrations.RemoveField(
            model_name='volumetype',
            name='polyresource_ptr',
        ),
        migrations.DeleteModel(
            name='Addon',
        ),
        migrations.DeleteModel(
            name='Aggregate',
        ),
        migrations.DeleteModel(
            name='AvailabilityZone',
        ),
        migrations.DeleteModel(
            name='Cinder',
        ),
        migrations.DeleteModel(
            name='Cloudpipe',
        ),
        migrations.DeleteModel(
            name='Credential',
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
        migrations.DeleteModel(
            name='Endpoint',
        ),
        migrations.DeleteModel(
            name='Flavor',
        ),
        migrations.DeleteModel(
            name='Glance',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Host',
        ),
        migrations.DeleteModel(
            name='Hypervisor',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Interface',
        ),
        migrations.DeleteModel(
            name='Keypair',
        ),
        migrations.DeleteModel(
            name='Keystone',
        ),
        migrations.DeleteModel(
            name='Limits',
        ),
        migrations.DeleteModel(
            name='Neutron',
        ),
        migrations.DeleteModel(
            name='NeutronAgent',
        ),
        migrations.DeleteModel(
            name='NeutronExtension',
        ),
        migrations.DeleteModel(
            name='NeutronFloatingIP',
        ),
        migrations.DeleteModel(
            name='NeutronNetwork',
        ),
        migrations.DeleteModel(
            name='NeutronPort',
        ),
        migrations.DeleteModel(
            name='NeutronQuota',
        ),
        migrations.DeleteModel(
            name='NeutronRouter',
        ),
        migrations.DeleteModel(
            name='NeutronSecurityGroup',
        ),
        migrations.DeleteModel(
            name='NeutronSecurityGroupRule',
        ),
        migrations.DeleteModel(
            name='NeutronSubnet',
        ),
        migrations.DeleteModel(
            name='NeutronSubnetPool',
        ),
        migrations.DeleteModel(
            name='Nova',
        ),
        migrations.DeleteModel(
            name='NovaLimits',
        ),
        migrations.DeleteModel(
            name='PolyResource',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='QOSSpec',
        ),
        migrations.DeleteModel(
            name='QuotaSet',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='Server',
        ),
        migrations.DeleteModel(
            name='ServerGroup',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Snapshot',
        ),
        migrations.DeleteModel(
            name='Token',
        ),
        migrations.DeleteModel(
            name='Transfer',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Volume',
        ),
        migrations.DeleteModel(
            name='VolumeType',
        ),
    ]
